version: '3.1'

services:

  https-portal:
    image: steveltn/https-portal:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      ACCESS_LOG: 'stdout'
      CUSTOM_NGINX_SERVER_CONFIG_BLOCK: 'proxy_read_timeout 300;'
      CUSTOM_NGINX_YASUFUMI_YOKOYAMA_GQ_CONFIG_BLOCK: |
        client_max_body_size 128M;
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      CUSTOM_NGINX_WWW_YASUFUMI_YOKOYAMA_GQ_CONFIG_BLOCK: |
        client_max_body_size 128M;
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      STAGE: 'production'
      #FORCE_RENEW: 'true'
      DOMAINS: >-
       yasufumi-yokoyama.gq -> http://192.168.1.20:8080
       ,www.yasufumi-yokoyama.gq -> http://192.168.1.20:8080
       ,linuxfun.org -> http://192.168.1.20:9080
       ,www.linuxfun.org -> http://192.168.1.20:9080
      SERVER_NAMES_HASH_BUCKET_SIZE: 64
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data:
