version: '3.1'

services:

  https-portal:
    image: steveltn/https-portal:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      ACCESS_LOG: 'stdout'
      WEBSOCKET: 'true'
      CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
        error_page 500 502 503 = /under_maintenance.html;
        location = /under_maintenance.html {
            return 200 "<html><head>\n<title>Under maintenance</title>\n</head><body>\n<h1>Under maintenance</h1>\n<p>The requested URL is now under maintenance.<br>Please visit again.<br>Thank you.</p>\n</body></html>";
            internal;
        }
        proxy_send_timeout 360s;
        proxy_read_timeout 360s;
      CUSTOM_NGINX_OFFICE_YASUFUMI_YOKOYAMA_GQ_CONFIG_BLOCK: |
        proxy_set_header Host $$http_host;
        proxy_set_header Connection "Upgrade";
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      CUSTOM_NGINX_WWW_OFFICE_YASUFUMI_YOKOYAMA_GQ_CONFIG_BLOCK: |
        client_max_body_size 512M;
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      CUSTOM_NGINX_YASUFUMI_YOKOYAMA_GQ_CONFIG_BLOCK: |
        client_max_body_size 512M;
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      CUSTOM_NGINX_WWW_YASUFUMI_YOKOYAMA_GQ_CONFIG_BLOCK: |
        client_max_body_size 512M;
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      CUSTOM_NGINX_HOLIDAYSFUN_ORG_CONFIG_BLOCK: |
        client_max_body_size 512M;
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      CUSTOM_NGINX_WWW_HOLIDAYSFUN_ORG_CONFIG_BLOCK: |
        client_max_body_size 512M;
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      CUSTOM_NGINX_LINUXFUN_ORG_CONFIG_BLOCK: |
        client_max_body_size 128M;
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      CUSTOM_NGINX_WWW_LINUXFUN_ORG_CONFIG_BLOCK: |
        client_max_body_size 128M;
        location = /.well-known/carddav     { return 301 /remote.php/dav/;  }
        location = /.well-known/caldav      { return 301 /remote.php/dav/;  }
        location ^~ /.well-known            { return 301 /index.php$uri;    }
      STAGE: 'production'
      #FORCE_RENEW: 'true'
      DOMAINS: >-
       yasufumi-yokoyama.gq -> http://192.168.100.100:8080
       ,www.yasufumi-yokoyama.gq -> http://192.168.100.100:8080
       ,office.yasufumi-yokoyama.gq -> http://192.168.100.200:9980
       ,www.office.yasufumi-yokoyama.gq -> http://192.168.100.200:9980
       ,holidaysfun.org -> http://192.168.100.150:19080
       ,www.holidaysfun.org -> http://192.168.100.150:19080
       ,linuxfun.org -> http://43.206.85.139:9080
       ,www.linuxfun.org -> http://43.206.85.139:9080
      SERVER_NAMES_HASH_BUCKET_SIZE: 64
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data:
